### ISSUE TITLE
trsh: ERROR (spawn error)

### ISSUE THREAD

**Issue by ghost** [fnzv/trsh#1]
Downloading & Installing Packages.. \n
Reading package lists... Done
Building dependency tree       
Reading state information... Done
dnsutils is already the newest version (1:9.11.2.P1-1ubuntu5).
nmap is already the newest version (7.60-1ubuntu4).
python is already the newest version (2.7.14-4).
mtr is already the newest version (0.92-1).
python-pip is already the newest version (9.0.1-2).
supervisor is already the newest version (3.3.1-1.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: telepot in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: urllib3>=1.9.1 in /usr/lib/python2.7/dist-packages (from telepot)
Enter your Telegram BOT Token: 
Trying to find out your Telegram sender-id..\n
Traceback (most recent call last):
  File "get-sender-id.py", line 13, in <module>
    response = bot.getUpdates()
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 1000, in getUpdates
    return self._api_request('getUpdates', _rectify(p))
  File "/usr/local/lib/python2.7/dist-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/usr/local/lib/python2.7/dist-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: (u'Not Found', 404, {u'error_code': 404, u'ok': False, u'description': u'Not Found'})
Enter your Telegram Sender ID: 
Configuring trsh as a service.. \n
Update supervisord.. \n
Starting trsh service.. \n
trsh: ERROR (spawn error)

os Ubuntu

**Comment by ghost** [comment]
oh, change dir in supervisor/conf.d/trsh.conf and all working ;)
